"""
PDRI Database Models
====================

SQLAlchemy models for persisting PDRI data.

Tables:
    - risk_findings: Risk findings generated by PDRI
    - score_history: Historical risk scores for trend analysis
    - audit_logs: Audit trail for compliance

Author: PDRI Team
Version: 1.0.0
"""

from datetime import datetime, timezone
from typing import Any, Optional
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from pdri.db.base import Base, TimestampMixin, generate_uuid, utc_now


# =============================================================================
# Risk Findings
# =============================================================================


class FindingDB(Base, TimestampMixin):
    """
    Persistent storage for risk findings.

    Maps to the RiskFinding Pydantic schema for API responses.

    Ownership:
        - Postgres owns the finding lifecycle (status, SLA, assignment)
        - Neo4j owns the risk computation (scores come from graph)
        - Findings reference graph entities but don't duplicate graph data
    """

    __tablename__ = "risk_findings"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    finding_id: Mapped[str] = mapped_column(
        String(32), unique=True, nullable=False, default=lambda: f"f-{uuid4().hex[:8]}"
    )

    # =========================================================================
    # Ownership & Multi-tenancy
    # =========================================================================
    tenant_id: Mapped[str] = mapped_column(
        String(64), nullable=False, default="default", index=True
    )
    owner_id: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True, index=True
    )  # User/team that owns this finding

    # =========================================================================
    # Correlation & Deduplication
    # =========================================================================
    fingerprint: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True
    )  # SHA256 of (entity_ids + finding_type + time_bucket)
    correlation_id: Mapped[Optional[str]] = mapped_column(
        String(36), nullable=True, index=True
    )  # Links to EventCorrelationDB

    # =========================================================================
    # Classification
    # =========================================================================
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    finding_type: Mapped[str] = mapped_column(
        String(50), nullable=False, default="risk_detected"
    )
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="medium"
    )  # low, medium, high, critical

    # =========================================================================
    # Risk Metrics (computed by Neo4j, stored here for queries)
    # =========================================================================
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)
    exposure_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    volatility_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sensitivity_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # =========================================================================
    # Entity References (IDs only - graph owns the data)
    # =========================================================================
    primary_entity_id: Mapped[str] = mapped_column(
        String(255), nullable=False, index=True
    )  # Main entity this finding is about
    primary_entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entities_involved: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=list
    )  # [{entity_id, entity_type, role}]
    exposure_path: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )  # Ordered entity IDs

    # =========================================================================
    # Evidence (references to source events)
    # =========================================================================
    evidence_refs: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=list
    )  # [{event_id, event_type, timestamp, source_system}]
    evidence_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # =========================================================================
    # Recommended Actions
    # =========================================================================
    recommended_actions: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=list
    )  # [{action, target, priority, risk_reduction_estimate}]

    # =========================================================================
    # Lifecycle & SLA
    # =========================================================================
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open"
    )  # open, acknowledged, in_progress, resolved, false_positive
    status_reason: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )  # Why status changed (resolution notes, false positive reason)
    assigned_to: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    sla_due_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )  # When this must be resolved by
    sla_breached: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    occurrence_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )  # How many times this fingerprint was seen

    # =========================================================================
    # Metadata
    # =========================================================================
    tags: Mapped[list] = mapped_column(ARRAY(String), nullable=False, default=list)
    metadata: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Schema versioning for Platform compatibility
    schema_version: Mapped[str] = mapped_column(
        String(20), nullable=False, default="1.0.0"
    )
    producer_version: Mapped[str] = mapped_column(
        String(20), nullable=False, default="1.0.0"
    )

    # Indexes for common queries
    __table_args__ = (
        Index("ix_findings_tenant_status", "tenant_id", "status"),
        Index("ix_findings_fingerprint", "fingerprint"),
        Index("ix_findings_severity", "severity"),
        Index("ix_findings_risk_score", "risk_score"),
        Index("ix_findings_created_at", "created_at"),
        Index("ix_findings_sla_due", "sla_due_at"),
        Index("ix_findings_primary_entity", "primary_entity_id"),
    )


# =============================================================================
# Score History
# =============================================================================


class ScoreHistoryDB(Base):
    """
    Historical risk scores for trend analysis.

    Stores point-in-time snapshots of entity scores.
    """

    __tablename__ = "score_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Entity reference
    entity_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)

    # Score components
    composite_score: Mapped[float] = mapped_column(Float, nullable=False)
    exposure_score: Mapped[float] = mapped_column(Float, nullable=False)
    volatility_score: Mapped[float] = mapped_column(Float, nullable=False)
    sensitivity_score: Mapped[float] = mapped_column(Float, nullable=False)

    # Factor breakdown (for explainability)
    factors: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Scoring metadata
    scoring_version: Mapped[str] = mapped_column(
        String(20), nullable=False, default="1.0.0"
    )
    calculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    __table_args__ = (
        Index("ix_score_history_entity_time", "entity_id", "calculated_at"),
        Index("ix_score_history_composite", "composite_score"),
    )


# =============================================================================
# Audit Trail
# =============================================================================


class AuditLogDB(Base):
    """
    Audit trail for compliance and forensics.

    Records all significant actions in the system.
    """

    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    log_id: Mapped[str] = mapped_column(
        String(36), unique=True, nullable=False, default=generate_uuid
    )

    # Action details
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    resource_type: Mapped[str] = mapped_column(String(50), nullable=False)
    resource_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Actor
    actor_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    actor_type: Mapped[str] = mapped_column(
        String(20), nullable=False, default="system"
    )  # user, service, system

    # Outcome
    outcome: Mapped[str] = mapped_column(
        String(20), nullable=False, default="success"
    )  # success, failure, partial
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Context
    request_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)
    user_agent: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Payload (before/after state for mutations)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Timestamp
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, index=True
    )

    __table_args__ = (
        Index("ix_audit_action", "action"),
        Index("ix_audit_resource", "resource_type", "resource_id"),
        Index("ix_audit_actor", "actor_id"),
    )


# =============================================================================
# Compliance Assessments
# =============================================================================


class ComplianceAssessmentDB(Base, TimestampMixin):
    """
    Stored compliance assessment results.
    """

    __tablename__ = "compliance_assessments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    assessment_id: Mapped[str] = mapped_column(
        String(36), unique=True, nullable=False, default=generate_uuid
    )

    # Framework
    framework: Mapped[str] = mapped_column(String(50), nullable=False)
    framework_version: Mapped[str] = mapped_column(String(20), nullable=False)

    # Scope
    scope_entity_ids: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )
    scope_type: Mapped[str] = mapped_column(
        String(20), nullable=False, default="full"
    )  # full, partial, targeted

    # Results
    overall_score: Mapped[float] = mapped_column(Float, nullable=False)
    compliance_status: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # compliant, non_compliant, partial
    controls_passed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    controls_failed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    controls_not_applicable: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )

    # Detailed results
    control_results: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    findings: Mapped[dict] = mapped_column(JSONB, nullable=False, default=list)
    recommendations: Mapped[dict] = mapped_column(JSONB, nullable=False, default=list)

    # Metadata
    assessed_by: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_assessment_framework", "framework"),
        Index("ix_assessment_status", "compliance_status"),
    )


# =============================================================================
# Event Ingestion Tracking
# =============================================================================


class ProcessedEventDB(Base):
    """
    Tracks processed events for idempotency.

    Prevents duplicate processing of the same event.
    Uses both event_id (exact match) and fingerprint (semantic match).
    """

    __tablename__ = "processed_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_id: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    source_system: Mapped[str] = mapped_column(String(255), nullable=False)

    # Fingerprint for semantic deduplication
    # SHA256 of (source_system + target_entity + event_type + time_bucket)
    fingerprint: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    # Link to correlation group
    correlation_id: Mapped[Optional[str]] = mapped_column(
        String(36), nullable=True, index=True
    )

    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    processing_result: Mapped[str] = mapped_column(
        String(20), nullable=False, default="success"
    )  # success, skipped_duplicate, failed

    __table_args__ = (
        Index("ix_processed_events_time", "processed_at"),
        Index("ix_processed_events_fingerprint_time", "fingerprint", "processed_at"),
    )


# =============================================================================
# Event Correlation
# =============================================================================


class EventCorrelationDB(Base):
    """
    Groups related events into a single correlation.

    The correlation layer sits between raw events and findings:
        Event → Correlation → Finding

    Multiple events with the same fingerprint within a time window
    are grouped into one correlation, which produces one finding.
    """

    __tablename__ = "event_correlations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    correlation_id: Mapped[str] = mapped_column(
        String(36), unique=True, nullable=False, default=generate_uuid
    )

    # =========================================================================
    # Correlation Identity
    # =========================================================================
    fingerprint: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True
    )  # SHA256 of correlation key
    correlation_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # ai_exposure, privilege_escalation, data_movement, etc.

    # =========================================================================
    # Time Window
    # =========================================================================
    window_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    window_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    window_duration_minutes: Mapped[int] = mapped_column(
        Integer, nullable=False, default=15
    )

    # =========================================================================
    # Event Aggregation
    # =========================================================================
    event_count: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    event_ids: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )  # All event_ids in this correlation
    event_types: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )  # Distinct event types seen

    # =========================================================================
    # Entity Context
    # =========================================================================
    primary_entity_id: Mapped[str] = mapped_column(
        String(255), nullable=False, index=True
    )
    primary_entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    related_entity_ids: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )

    # =========================================================================
    # Aggregated Signals
    # =========================================================================
    max_severity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="low"
    )  # Highest severity among events
    sensitivity_tags: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, default=list
    )  # Union of all sensitivity tags
    total_data_volume: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )  # Sum of data_volume_estimate

    # =========================================================================
    # Output Reference
    # =========================================================================
    finding_id: Mapped[Optional[str]] = mapped_column(
        String(32), nullable=True, index=True
    )  # The finding generated from this correlation
    finding_generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # =========================================================================
    # State
    # =========================================================================
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open"
    )  # open (accepting events), closed (finding generated), expired
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    __table_args__ = (
        Index("ix_correlation_fingerprint_window", "fingerprint", "window_start"),
        Index("ix_correlation_status", "status"),
        Index("ix_correlation_primary_entity", "primary_entity_id"),
    )
